[package]
authors = ["rwxbytes <rwxbytes@proton.me>"]
description = "A library for interacting with ElevenLabs API"
edition = "2021"
keywords = ["elevenlabs", "tts", "text-to-speech", "voice-clone", "ai"]
license = "MIT"
name = "elevenlabs_rs"
readme = "README.md"
repository = "https://github.com/rwxbytes/elevenlabs_rs"
version = "0.2.0"

[dependencies]
async-native-tls = {version = "0.5.0", default-features = false, features = [
  "runtime-tokio",
]}
bytes = "1.4.0"
chrono = "0.4.26"
comparable = {version = "0.5.4", features = ["derive"]}
futures-util = "0.3.28"
http-body = "1.0.0-rc.2"
http-body-util = "0.1.0-rc.3"
hyper = {version = "1.0.0-rc.4", features = ["full"]}
pin-project-lite = "0.2.10"
rand = "0.8.5"
rodio = "0.17.1"
serde = {version = "1.0.173", features = ["derive"]}
serde_bytes = "0.11.12"
serde_json = "1.0.103"
thiserror = "1.0.43"
tokio = {version = "1", features = ["rt", "time", "net"]}
